plugins:
  - jekyll-polyglot
languages: ["en", "es"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false
t:
    en:
        index:
            name: "Index"
            url: "/"
        #blog:
        #    name: "Blog"
        #    url: "/blog/"
        projects:
            name: "Projects"
            url: "/projects/"
        about:
            name: "About Me"
            url: "/about/"
    es:
        index:
            name: "Index"
            url: "/"
        #blog:
        #    name: "Blog"
        #    url: "/blog/"
        projects:
            name: "Proyectos"
            url: "/projects/"
        about:
            name: "Sobre Mí"
            url: "/about/"
strings:
    forWhom:
        en: "For whom?:"
        es: "¿Para quién?:"
    when:
        en: "When?:"
        es: "¿Cuándo?:"
    techs:
        en: "Used technologies:"
        es: "Tecnologías usadas:"
    hello:
        en: "Hello, Carlos"
        es: "Hola, Carlos"